CREATE TABLE IF NOT EXISTS txnType (
  txnTypeId INTEGER PRIMARY KEY,
  txnType TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS acctType (
  acctTypeId INTEGER PRIMARY KEY,
  acctType TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS transactions (
  txnId INTEGER PRIMARY KEY,
  txnTypeId INTEGER NOT NULL,
  description TEXT NOT NULL,
  date TEXT NOT NULL,
  tags TEXT,
  attachment TEXT,
  FOREIGN KEY (txnTypeId) REFERENCES txnType (txnTypeId) ON
  DELETE NO ACTION ON
  UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS accounts (
  acctId INTEGER PRIMARY KEY,
  acctTypeId INTEGER NOT NULL,
  name TEXT NOT NULL,
  parentId INTEGER,
  icon TEXT,
  currency TEXT NOT NULL,
  hidden INTEGER NOT NULL,
  FOREIGN KEY (acctTypeId) REFERENCES acctType (acctTypeId) ON
  DELETE NO ACTION ON
  UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS postings (
  postingId INTEGER PRIMARY KEY,
  txnId INTEGER NOT NULL,
  acctId INTEGER NOT NULL,
  amount REAL NOT NULL,
  currency TEXT NOT NULL,
  FOREIGN KEY (txnId) REFERENCES transactions (txnId) ON
  DELETE CASCADE ON
  UPDATE NO ACTION FOREIGN KEY (acctId) REFERENCES accounts (acctId) ON
  DELETE CASCADE ON
  UPDATE NO ACTION
);