name: Tauri Android Build

on:
  push:
    branches:
      - main

jobs:
  android-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-linux-android"

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.3.13750724"

      - name: Set env vars
        run: |
          echo "JAVA_HOME=/opt/android-studio/jbr" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_HOME/ndk/$(ls -1 $ANDROID_HOME/ndk)" >> $GITHUB_ENV

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build Tauri Android App
        run: pnpm tauri android build --apk --target aarch64 --debug

      - name: Read version from tauri.conf.json
        id: tauri_version
        run: echo "version=$(jq -r '.version' src-tauri/tauri.conf.json)" >> $GITHUB_OUTPUT

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          tag_name: "android-v${{ steps.tauri_version.outputs.version }}"
          name: "Android v${{ steps.tauri_version.outputs.version }}"
          files: src-tauri/gen/android/app/build/outputs/apk/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
